title: "Rust ハンズオン -- 文法編 --"
summary: "Rust ハンズオンで使用した資料です。文法に関して一通りマスターしてもらうことを目的として作成されています。"
topics: ["rust"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
